### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by ojczeo** [rossta/vue-pdfjs-demo#1]
Hello @rossta, what's license of this project? Are you planning to release this as `npm` package?

**Comment by rossta** [comment]
@ojczeo If with enough interest, yes, I would consider extracting the core of this demo into a reusable package. Interested?

**Comment by ojczeo** [comment]
Thanks, License info was the most important. I'm creating fork of your code to provide image-based docs viewer (instead of PDF URL it would parse Array of image URLs). Your code logic is really well designed, I wonder about releasing my fork of that viewer as npm package, but it would be nice to see your package first at npm I think =)

**Comment by rossta** [comment]
@ojczeo Thanks, I'll consider it. Some work would have to be done to make it more generalized and to introduce a build step to produce the distribution.
