### ISSUE TITLE
Can't update to new pdf when I change url in .env file

### ISSUE THREAD

**Issue by gallard28** [rossta/vue-pdfjs-demo#20]
I cloned the repo and have been trying to understand it better. When I change the url in the .env file, the pdf displayed does not change. 

Is there somewhere else I also have to make that change?

**Comment by TrungMiichisoft** [comment]
@gallard28 
When you change .env file, run yarn serve again or You can change the url in App.vue

**Comment by gallard28** [comment]
> @gallard28
> When you change .env file, run yarn serve again or You can change the url in App.vue

@tannnmiichi 's  solution works. Thank you!
