### ISSUE TITLE
How to access debug log

### ISSUE THREAD

**Issue by punit5658** [rossta/vue-pdfjs-demo#26]
I impressed with your developed demo in vuejs. I seen that you have used debug and set log some of placed but can you please help me how to access it. Any configuration for that?
I use npm run serve to run project.

**Comment by rossta** [comment]
The debug package behavior in the browser is keyed off the `window.localStorage.debug` setting. When there is no value, no messages are output to console. Set it to a pattern and reload the page to view messages, e.g. to see all messages, I would set `window.localStorage.debug = "*"` 

https://www.npmjs.com/package/debug#browser-support
