### ISSUE TITLE
ReferenceError : window is not defined

### ISSUE THREAD

**Issue by eMahtab** [rossta/vue-pdfjs-demo#3]
Getting this error on running the demo from branch tutorial/part-1-simple-document

<img width="1336" alt="vue-pdfjs-demo_and_logo_png_ _1-pdf-viewer" src="https://user-images.githubusercontent.com/6348083/44014886-d82c6daa-9eeb-11e8-9849-b81e296712b0.png">

**Comment by eMahtab** [comment]
Seems to be some issue with webpack web-worker, I created a new project with vue init webpack, copied the components file and everything worked. Thanks

**Comment by clementdevos** [comment]
Be sure to add `globalObject: "this"` in the output object of webpack! :)

**Comment by hannajs** [comment]
Edit (or create) vue.config.js and change webpack configuration there:
`module.exports = { configureWebpack: config => { config.output.globalObject = "this"; } }`
